# Generated by Django 3.1 on 2020-09-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jefes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='grupo',
        ),
        migrations.AddField(
            model_name='salon',
            name='grupo',
            field=models.ManyToManyField(related_name='salones', to='sgi.Grupo_Investigacion'),
        ),
        migrations.CreateModel(
            name='Persona_Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_ingreso', models.DateTimeField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_grupo', to='sgi.grupo_investigacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_grupo', to='sgi.persona')),
            ],
        ),
    ]
