# Generated by Django 3.1 on 2020-09-19 20:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sgi', '0002_auto_20200919_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('CI', models.PositiveBigIntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('user_role', models.CharField(choices=[('', ''), ('admin', 'Administrator'), ('jefe', 'Group Chief'), ('user', 'Group Member')], max_length=8)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='sgi.grupo_investigacion')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Jefes',
        ),
        migrations.RemoveField(
            model_name='persona_grupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='persona_grupo',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Persona_Grupo',
        ),
    ]
