# Generated by Django 3.1 on 2020-09-20 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0004_auto_20200919_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='f_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
