# Generated by Django 3.1 on 2020-09-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0007_auto_20200920_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='grupo',
        ),
    ]
