# Generated by Django 3.1 on 2020-09-21 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0008_remove_salon_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medio',
            name='d_devolucion',
        ),
        migrations.RemoveField(
            model_name='medio',
            name='user',
        ),
        migrations.AlterField(
            model_name='medio',
            name='prestado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_devolucion', models.DateTimeField(auto_now_add=True)),
                ('medio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='sgi.medio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='sgi.user')),
            ],
        ),
    ]
